[features]
seeds = false
skip-lint = false

[programs.localnet]
euro2024_betting = "DULGDdPomhYSSHvdzGKpoGip3FuiSoTZ9oEU4bNpCvKr"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "Localnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
