[features]
seeds = false
skip-lint = false

[programs.localnet]
euro_2024_betting = "FgHdZx3HP6rA9zcc9pCsjpZhGbePnErG28RjkTmujoe3"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "Localnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
